name: Semgrep Analysis

on:
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # Hacer checkout del código
      - uses: actions/checkout@v4

      # Instalar Semgrep y prospector-html
      - name: Set up tools (Semgrep + prospector-html)
        run: |
          pip install semgrep prospector2html

      # Ejecutar análisis Semgrep en formato JSON dentro de la carpeta Markdown2Video
      - name: Run Semgrep scan
        run: semgrep scan --config='p/default' Markdown2Video --json --output semgrep.json

      # Convertir los resultados JSON a un reporte HTML con prospector-html
      - name: Generate HTML report
        run: |
          mkdir -p html-report
          prospector-html --input semgrep.json --output html-report/index.html --filter semgrep || true

      # Verificar que el reporte HTML fue generado
      - name: Verify HTML report exists
        run: test -f html-report/index.html

      # Publicar el reporte HTML en GitHub Pages
      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html-report
          publish_branch: gh-pages
          destination_dir: reports/html
